#!/bin/bash

# order in which to compile coffee files
COMPILE_ORDER=""
COMPILE_ORDER="${COMPILE_ORDER} coffee/util.coffee"
COMPILE_ORDER="${COMPILE_ORDER} coffee/chatter/*.coffee"
COMPILE_ORDER="${COMPILE_ORDER} coffee/malice/*.coffee"

echo "Coffeescript Compilation Order:${COMPILE_ORDER}"
coffee --compile --watch --join malice/js/malice.js ${COMPILE_ORDER} &
dev_appserver.py malice


