application: be-my-secretary
version: 1-simplified-hayes
runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /js
    static_dir: js

  - url: /libs
    static_dir: libs

  - url: /css
    static_dir: css

  - url: /imgs
    static_dir: imgs

  # - url: /libs/blitzer/images
  #   static_dir: libs/blitzer/images

  # - url: /admin.*
  #   script: main.app
  #   login: admin

  - url: .*
    script: main.app

libraries:
  - name: webapp2
    version: "2.5.1"